"""Generate a beautiful HTML daily brief page."""

import re
from datetime import datetime, timezone, timedelta
from src.models import BriefResult

CST = timezone(timedelta(hours=8))


def generate_html(brief: BriefResult) -> str:
    """Generate a standalone HTML page from the brief."""
    date_str = datetime.now(CST).strftime("%Y-%m-%d")
    items_html = _format_items(brief.summary_text)
    raw_count = brief.raw_count

    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI Daily Brief - {date_str}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    background: #f7f8fa;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC",
                 "Microsoft YaHei", "Helvetica Neue", sans-serif;
    color: #333;
    line-height: 1.6;
    padding: 20px 16px 40px;
  }}
  .container {{ max-width: 680px; margin: 0 auto; }}

  /* Header */
  .header {{
    text-align: center;
    padding: 30px 20px 24px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border-radius: 16px;
    color: #fff;
    margin-bottom: 20px;
  }}
  .header h1 {{ font-size: 24px; font-weight: 700; margin-bottom: 6px; }}
  .header .sub {{ font-size: 14px; opacity: 0.85; }}
  .header .date {{ font-size: 13px; opacity: 0.7; margin-top: 8px; }}
  .header .badge {{
    display: inline-block;
    background: rgba(255,255,255,0.2);
    padding: 4px 14px;
    border-radius: 20px;
    font-size: 13px;
    margin-top: 10px;
  }}

  /* Summary card */
  .summary-card {{
    background: #fff;
    border-radius: 12px;
    padding: 18px 20px;
    margin-bottom: 16px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.06);
    border-left: 4px solid #667eea;
  }}
  .summary-card p {{ font-size: 15px; color: #555; }}

  /* Section title */
  .section-title {{
    font-size: 18px;
    font-weight: 700;
    color: #333;
    margin: 24px 0 14px;
    display: flex;
    align-items: center;
    gap: 8px;
  }}
  .section-title::after {{
    content: "";
    flex: 1;
    height: 1px;
    background: #e5e5e5;
  }}

  /* Item card */
  .item {{
    background: #fff;
    border-radius: 12px;
    padding: 16px 18px;
    margin-bottom: 12px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.06);
    transition: transform 0.1s;
  }}
  .item:hover {{ transform: translateY(-1px); box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
  .item .num {{
    display: inline-block;
    width: 24px;
    height: 24px;
    background: #667eea;
    color: #fff;
    font-size: 13px;
    font-weight: 700;
    text-align: center;
    line-height: 24px;
    border-radius: 50%;
    margin-right: 8px;
    flex-shrink: 0;
  }}
  .item .title-line {{
    display: flex;
    align-items: flex-start;
    gap: 0;
  }}
  .item .title-text {{
    font-size: 15px;
    font-weight: 500;
    color: #1a1a1a;
    line-height: 1.5;
    flex: 1;
  }}
  .item .source {{
    display: inline-block;
    font-size: 11px;
    color: #667eea;
    background: #f0f0ff;
    padding: 1px 8px;
    border-radius: 4px;
    margin-left: 6px;
    font-weight: 400;
    white-space: nowrap;
  }}
  .item .desc {{
    font-size: 14px;
    color: #888;
    line-height: 1.6;
    margin-top: 6px;
    padding-left: 32px;
  }}

  /* Trend */
  .trend {{
    background: linear-gradient(135deg, #f0f0ff 0%, #faf0ff 100%);
    border-radius: 12px;
    padding: 18px 20px;
    margin: 20px 0;
    border-left: 4px solid #764ba2;
  }}
  .trend h3 {{ font-size: 15px; color: #764ba2; margin-bottom: 6px; }}
  .trend p {{ font-size: 14px; color: #555; }}

  /* Footer */
  .footer {{
    text-align: center;
    padding: 24px 0 8px;
    font-size: 13px;
    color: #bbb;
  }}
  .footer a {{ color: #667eea; text-decoration: none; }}

  /* Stats bar */
  .stats {{
    display: flex;
    justify-content: center;
    gap: 24px;
    background: #fff;
    border-radius: 12px;
    padding: 12px 20px;
    margin: 16px 0;
    box-shadow: 0 1px 4px rgba(0,0,0,0.06);
    font-size: 13px;
    color: #888;
  }}
  .stats span {{ display: flex; align-items: center; gap: 4px; }}
</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1>📡 AI Daily Brief</h1>
    <div class="sub">AI 工具资讯每日日报</div>
    <div class="date">{date_str}</div>
    <div class="badge">共收录 {raw_count} 条资讯</div>
  </div>

  {items_html}

  <div class="footer">
    <p>Generated by AI Daily Brief · <a href="https://github.com/hcj1206/hecj-ai-daily-brief">GitHub</a></p>
    <p style="margin-top:4px;">每天 09:00 自动更新</p>
  </div>

</div>
</body>
</html>"""


def _format_items(summary_text: str) -> str:
    """Parse the DeepSeek summary text and generate HTML for items."""
    lines = summary_text.strip().split("\n")
    parts = []
    i = 0
    item_num = 1

    while i < len(lines):
        line = lines[i].strip()
        if not line:
            i += 1
            continue

        # Section header
        if line.startswith("###"):
            text = line.lstrip("#").strip()
            parts.append(f'<div class="section-title">📌 {text}</div>')
            i += 1
            continue

        # Horizontal rule
        if line.startswith("---"):
            parts.append('<hr style="border: none; border-top: 1px solid #e5e5e5; margin: 16px 0;">')
            i += 1
            continue

        # Numbered item: "1. Title [Source]"
        m = re.match(r"^\d+[\.\u3001]\s*(.+)$", line)
        if m:
            item_text = m.group(1)

            # Extract source tag
            source_tag = ""
            tag_m = re.search(r"\[([^\]]+)\]", item_text)
            if tag_m:
                source_tag = tag_m.group(1)
                item_text = re.sub(r"\s*\[([^\]]+)\]", "", item_text)

            # Look ahead for description
            desc_text = ""
            if i + 1 < len(lines):
                nx = lines[i + 1].strip()
                is_desc = nx.startswith("\u4e00\u53e5\u8bdd\u7b80\u4ecb")  # 一句话简介
                is_desc = is_desc or nx.startswith("\u7b80\u4ecb")  # 简介
                if is_desc and not nx.startswith("###") and not nx.startswith("---"):
                    dm = re.search(r"[:：]\s*(.+)", nx)
                    if dm:
                        desc_text = dm.group(1)
                    else:
                        desc_text = nx
                    i += 1

            # Render item
            source_html = f'<span class="source">{source_tag}</span>' if source_tag else ""
            desc_html = f'<div class="desc">{desc_text}</div>' if desc_text else ""

            parts.append(
                f'<div class="item">'
                f'<div class="title-line">'
                f'<span class="num">{item_num}</span>'
                f'<span class="title-text">{item_text}{source_html}</span>'
                f'</div>'
                f'{desc_html}'
                f'</div>'
            )
            item_num += 1
            i += 1
            continue

        # Bold trend summary
        if line.startswith("**") and "**" in line[2:]:
            clean = line.replace("**", "")
            parts.append(
                f'<div class="trend"><h3>📊 今日趋势</h3><p>{clean}</p></div>'
            )
            i += 1
            continue

        # Lines with source tags (not numbered)
        if "[" in line and "]" in line:
            formatted = re.sub(
                r"\[([^\]]+)\]",
                r'<span class="source">[\1]</span>',
                line,
            )
            parts.append(f'<p style="font-size: 15px; color: #555; margin: 8px 0;">{formatted}</p>')
            i += 1
            continue

        # Regular paragraph
        parts.append(f'<p style="font-size: 15px; color: #555; margin: 8px 0;">{line}</p>')
        i += 1

    return "\n".join(parts)
